// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load dotenv/config for local development (Railway doesn't use .env files)
// dotenv/config only sets variables that don't already exist, so Railway's env vars take precedence
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Log immediately when module loads to verify it's being executed
console.log("[Prisma Config] Module loading...");
console.log("[Prisma Config] DATABASE_URL at load time:", process.env.DATABASE_URL ? process.env.DATABASE_URL.substring(0, 30) + "..." : "NOT FOUND");
console.log("[Prisma Config] All DATABASE/DB env vars:", Object.keys(process.env).filter(k => k.includes("DATABASE") || k.includes("DB")).join(", ") || "none");

// Get DATABASE_URL from environment - read directly
const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  console.error("[Prisma Config] ERROR: DATABASE_URL is missing!");
  console.error("[Prisma Config] Available env keys (first 20):", Object.keys(process.env).slice(0, 20).join(", "));
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Read directly from process.env - Prisma 7.x requires this in config file
    url: databaseUrl || "",
  },
});
