// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load dotenv/config for local development (Railway doesn't use .env files)
// dotenv/config only sets variables that don't already exist, so Railway's env vars take precedence
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Get DATABASE_URL from environment
// Railway injects this when services are linked
// Read it directly - it should be available when Prisma CLI runs
const databaseUrl = process.env.DATABASE_URL;

// Debug logging to help diagnose issues
if (!databaseUrl) {
  console.warn("Warning: DATABASE_URL not found in environment.");
  console.warn("Available env vars with 'DATABASE' or 'DB':", 
    Object.keys(process.env).filter(k => k.includes("DATABASE") || k.includes("DB")).join(", ") || "none");
} else {
  console.log("DATABASE_URL found in config:", databaseUrl.substring(0, 30) + "...");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7.x requires this - it will throw its own error if missing
    url: databaseUrl || "",
  },
});
